model_training:
  test_size: 0.2
  random_state: 42

models:
  logistic_regression:
    C: 1.0
    max_iter: 1000
    class_weight: balanced

  random_forest:
    n_estimators: 200
    max_depth: 12
    random_state: 42
    class_weight: balanced_subsample

  xgboost:
    n_estimators: 300
    max_depth: 6
    learning_rate: 0.05
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
    scale_pos_weight: 577

  lightgbm:
    n_estimators: 300
    learning_rate: 0.05
    max_depth: -1
    random_state: 42
    class_weight: balanced